#ddev-generated
services:
  mockoon:
    container_name: ddev-${DDEV_SITENAME}-mockoon
    hostname: ${DDEV_SITENAME}-mockoon
    image: mockoon/cli:latest
    command: ["-d", "api-mocks/demo.json"]
    networks: [default, ddev_default]
    restart: "no"
    expose:
      - "3000"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".ddev/api-mocks:/api-mocks"
    - ".:/mnt/ddev_config"
    
volumes:
  api-mocks: